import { Box, Heading, SimpleGrid } from "@chakra-ui/react";

const RecommendationsScreen = () => {
  return (
    <Box>
      <Heading mb={8}>Recomendaciones</Heading>
      <SimpleGrid columns={4} spacing={10} w="full" h="container.sm">
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
        <Box
          w="100%"
          h="100%"
          borderColor="gray.300"
          borderWidth={1}
          borderStyle="solid"
          borderRadius={8}
        />
      </SimpleGrid>
    </Box>
  );
};

export default RecommendationsScreen;
